global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'mlops-project'
    environment: 'development'

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  # - "alerts.yml"

# Scrape configurations